package message;

public enum MessageType {
    FILE_BACKUP,
    FILE_RESTORE,
    FILE_DELETE,
    NODE_SUCCESSOR,
    NODE_PREDECESSOR,
    LOOKUP_FILE,
    CHORD_JOIN,
    CHORD_ACK,
    CHORD_LOOKUP,
    CHORD_PUT,
    CHORD_ANNOUNCE_PEER,
    CHORD_PREDECESSOR_HERE
}